### ISSUE TITLE
Suggestion: Use the containment operator to speed up metadata equality

### ISSUE THREAD

**Issue by ankane** [supabase/vecs#11]
Hi @olirice, thanks for creating this library!

Using the containment operator (`@>`) for equality should speed up metadata filtering, as it'll allow the GIN index to used. From [the docs](https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING): "The default GIN operator class for jsonb supports queries with the key-exists operators ?, ?| and ?&, the containment operator @>, and the jsonpath match operators @? and @@."

You can also use `jsonb_path_ops` for a smaller index size. "The non-default GIN operator class jsonb_path_ops does not support the key-exists operators, but it does support @>, @? and @@."

```python
import json
import psycopg
import random

conn = psycopg.connect(dbname='vecs', autocommit=True)
conn.execute('CREATE TABLE docs (id bigserial PRIMARY KEY, metadata jsonb)')

for _ in range(100):
    metadata = []
    for _ in range(10000):
        md = {
            'a': random.randint(1, 10000),
            'b': random.choice(['value' + str(i) for i in range(1, 100)])
        }
        metadata.append(json.dumps(md))

    sql = 'INSERT INTO docs (metadata) VALUES ' + ','.join(['(%s)' for _ in metadata])
    conn.execute(sql, metadata)

conn.execute('CREATE INDEX ON docs USING gin (metadata jsonb_path_ops)')

# no index
res = conn.execute("EXPLAIN ANALYZE SELECT * FROM docs WHERE metadata -> 'a' = '1'").fetchall()
print('\n'.join([r[0] for r in res]))

# index
res = conn.execute("""EXPLAIN ANALYZE SELECT * FROM docs WHERE metadata @> '{"a": 1}'""").fetchall()
print('\n'.join([r[0] for r in res]))

# no index
res = conn.execute("""EXPLAIN ANALYZE SELECT * FROM docs WHERE metadata -> 'b' = '"value1"'""").fetchall()
print('\n'.join([r[0] for r in res]))

# index
res = conn.execute("""EXPLAIN ANALYZE SELECT * FROM docs WHERE metadata @> '{"b": "value1"}'""").fetchall()
print('\n'.join([r[0] for r in res]))
```

Edit: More from the docs on `jsonb_path_ops`

> Although the jsonb_path_ops operator class supports only queries with the @>, @? and @@ operators, it has notable performance advantages over the default operator class jsonb_ops. A jsonb_path_ops index is usually much smaller than a jsonb_ops index over the same data, and the specificity of searches is better, particularly when queries contain keys that appear frequently in the data. Therefore search operations typically perform better than with the default operator class.

**Comment by olirice** [comment]
> Using the containment operator (@>) for equality should speed up metadata filtering

thanks!

> use jsonb_path_ops for a smaller index size. "The non-default GIN operator class jsonb_path_ops does not support the key-exists operators, but it does support @>, @? and @@."

we don't support key exists filters so that sounds great

--

how does #12 look, does that address both the way you expected?

**Comment by ankane** [comment]
Yeah, looks great!

**Comment by ankane** [comment]
Just realized it probably shouldn't use containment if the query is a list or dict, since both the following are true but not equal:

```sql
SELECT '{"a": [1, 2, 3]}'::jsonb @> '{"a": [1]}';
SELECT '{"a": {"b": 1, "c": 2}}'::jsonb @> '{"a": {"b": 1}}';
```

**Comment by olirice** [comment]
makes sense, thanks

I added tests for the various edge cases to make sure its all working properly

The trouble with re-checking for equality in python after the results are returned is that it makes it difficult to get the exact number of results the user requested without potentially fetching more matches from the database. To avoid that, the containment optimization is limited to when the user provides a single value e.g. `6` or `"abc"`.
