### ISSUE TITLE
Can't connect to Supabase

### ISSUE THREAD

**Issue by krrishdholakia** [supabase/vecs#15]
**Describe the bug**
I'm trying to connect vecs to my supabase db but it's throwing a sql error. I tried to install psycogs-binary and sqlalchemy but that didn't help either

**To Reproduce**
1. Try connecting vecs to your supabase db in a google colab

**Expected behavior**
I'd expect it to connect

**Screenshots**
<img width="1078" alt="Screen Shot 2023-06-07 at 3 40 50 PM" src="https://github.com/supabase/vecs/assets/17561003/1290f98c-d5ae-4469-a433-3aba88def4bd">

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - vecs version: e.g. 0.2.6

**Additional context**

**Comment by krrishdholakia** [comment]
replaced my db connection for the one in the example

**Comment by olirice** [comment]
sqlalchemy dropped support for alias `postgres` for the dialect `postgresql` in version 1.4

You can avoid that error by using `postgresql://` to `postgres://` in the connection string

**Comment by olirice** [comment]
great! from the thumbs up on the previous message it sounds like that worked. please re-open this issue if you're still running into it
