### ISSUE TITLE
No function to close the connection

### ISSUE THREAD

**Issue by cnmoro** [supabase/vecs#2]
Currently there is no function to close the connection with postgres.
Have tried to access the Session object and close it, but didn't work.

**Comment by olirice** [comment]
Propose adding

```python
vx.disconnect()
```

and 

```
with vecs.Client(...) as vx:
   ...
```

for manual and auto-closing options.

Should also add a note in the docs to use the connection pooler connection string rather than direct connection when hosting with supabase
