### ISSUE TITLE
Openai Example on documentation doesn't seem to work well. 

### ISSUE THREAD

**Issue by Rohianon** [supabase/vecs#36]
Hi,

I am trying to run this piece of example, however, it looks like it is not working like expected.

```python

import openai

openai.api_key = '<OPENAI-API-KEY>'

dataset = [
    "The cat sat on the mat.",
    "The quick brown fox jumps over the lazy dog.",
    "Friends, Romans, countrymen, lend me your ears",
    "To be or not to be, that is the question.",
]

embeddings = []

for sentence in dataset:
    response = openai.Embedding.create(
        model="text-embedding-ada-002",
        input=[sentence]
    )
    embeddings.append((sentence, response["data"][0]["embedding"]))

```

I am getting an error on dimensions. 

![image](https://github.com/supabase/vecs/assets/41194018/0e2e0e56-aa8d-4a51-a8a6-6eb43c606c2e)

When I try fixing it  by adding an id, it however gives another unexpected error of this format.
![image](https://github.com/supabase/vecs/assets/41194018/9b99d673-b3f3-4257-b519-320cb650a9c1)

how could this be resolve?

**Comment by olirice** [comment]
thanks for reporting

I have updated the doc https://supabase.github.io/vecs/integrations_openai/ but if may take 20 minutes to go through

The fix is the change
```python
embeddings.append((sentence, response["data"][0]["embedding"]))
```
to
```python
embeddings.append((sentence, response["data"][0]["embedding"], {}))
```

please let me know if you have any trouble after that change

**Comment by Rohianon** [comment]
I have even tried to make the function resemble the openai one, but still stuck at it. 

```
def generate_embeddings(documents):
    # docs = [(str(uuid.uuid4()), embed(data=str(doc.page_content)), doc.metadata) for doc in documents]
    embeddings = []

    for document in documents:
        response = openai.Embedding.create(
            model="text-embedding-ada-002",
            input=[document]
        )
        embeddings.append((document, response["data"][0]["embedding"], {}))
    return embeddings
```

Your aid will really be appreciated.

**Comment by Rohianon** [comment]
The error is being raised during upserting. 

```
    # upsert the embeddings into the collection
    docs.upsert(records=docs)
```

**Comment by olirice** [comment]
marking resolved

the issue was a variable naming clash

**Comment by olirice** [comment]
@Rohianon I wasn't able to reproduce the langchain/supabase-py incompatibility with pedantic. Could you please try to create a minimal reproducible example and open that issue on https://github.com/supabase-community/supabase-py ?

we definitely want to be compatible with langchain

**Comment by Rohianon** [comment]
Sure thing, @olirice . Will be able to do so and share the examples.
