### ISSUE TITLE
What is the relationship between SupabaseVectorStore integrated with langchain and this library

### ISSUE THREAD

**Issue by bllchmbrs** [supabase/vecs#38]
# Summary
[summary]: #summary

I'm pretty confused just reading through the code and trying to navigate vectors with supabase. It seems to me that they _should_ be related, but aren't. There's no documentation on how they should be used together or whether they should, but they're both related to supabase - which one am I supposed to use? How should I be thinking about using them together?

**Comment by olirice** [comment]
There is no association between vecs and langchain.

vecs is a dedicated client for pgvector. langchain provides a common interface to various vector stores, including pgvector on supabase.

vecs aims to take advantage of lower level features that are only applicable to pgvector like performant ANN indexing and metadata filtering. In contrast, langchain is more portable
