### ISSUE TITLE
Empty Description on PyPI

### ISSUE THREAD

**Issue by iwootten** [supabase/vecs#44]
The package description on pypi for vecs doesn't have a lot of detail and might imply inactivity. Would be great if it could be updated.

Pretty sure it just needs appropriate fields in the pyproject.toml to publish from the readme.

![Screenshot 2023-09-14 at 16 05 04](https://github.com/supabase/vecs/assets/3598161/04700c82-7dca-44c9-b284-ab0aa01a1d6b)

**Comment by olirice** [comment]
thanks for reporting, now updated on pypi https://pypi.org/project/vecs/
