### ISSUE TITLE
Option to load private models from Higgingface

### ISSUE THREAD

**Issue by Bhanu-py** [supabase/vecs#46]
**Describe the bug**
Cannot load the private models from the HuggingFace, No **kwargs are passed to the ST() in the class TextEmbedding(AdapterStep)

**Expected behavior**
'use_auth_token' = None can be passed in the init() and ST()

**Screenshots**

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - vecs version: e.g. 0.2.6

**Additional context**
Did add manually, But it was problem when I deploy my application in the cloud when it installs.

**Comment by olirice** [comment]
Would you be interested in opening a PR adding these to the TextEmbedding adapter?

**Comment by Bhanu-py** [comment]
Sure, I'd be happy to open a PR to add the 'use_auth_token' option to the TextEmbedding adapter. I'll start working on it and will submit the PR once it's ready.
