### ISSUE TITLE
Support for Metadata Projection

### ISSUE THREAD

**Issue by sri-oli** [supabase/vecs#64]
It would be great if we can select specific fields to be queried rather than ship the entire metadata column over the wire. This is helpful if there is a lot of metadata.

**Comment by olirice** [comment]
I can see the benefit for projects that make heavy use of metadata but this would be a big increase in scope as we'd have to introduce our own language for projections and translate it into Postgres compatible json operators.

Overall I don't think its enough of a problem to justify the additional complexity we'd have to introduce so I'm going to close this for now
