### ISSUE TITLE
Deleting with filters not working (Package mismatch with source code?)

### ISSUE THREAD

**Issue by kevinco26** [supabase/vecs#66]
**Describe the bug**
Trying to use the function in collection.delete() that has an optional filters parameter to delete with specific metadata.
The source code has it: https://github.com/supabase/vecs/blob/b780f9977cbee2bfd8e3bcdf41c4bff8957092d4/src/vecs/collection.py#L381

As well as **official documentation**  https://supabase.com/docs/guides/ai/python/api#deleting-vectors

When I download the latest vecs package (0.4.1) I am NOT seeing these changes locally. My hunch is that there's a package mismatch between what's deployed and the source code.
 
**To Reproduce**
1.Start a python virtual environment. 
2.pip install vecs
3. run the following python code (substitute connection strings)
```
import vecs
vx = vecs.create_client(<connection>)
collection_name = 'collection_name'
db = vx.get_or_create_collection(name=collection_name, dimension=1536)
db.delete(filters={"foo": {"$eq": "bar"}})
```

you will get:` TypeError: Collection.delete() got an unexpected keyword argument 'filters'`

**Expected behavior**
Expecting the code to run the source code in github and actually delete the vectors associated with a particular metadata.

**Comment by olirice** [comment]
Deleting by metadata was introduced was available on master but not in a release yet. I just published 0.4.2 and you can now install that feature from pypi

thanks
