### ISSUE TITLE
Remove limit of 1 entry per filter

### ISSUE THREAD

**Issue by VictorAny** [supabase/vecs#69]
# Summary
[summary]: #summary
Hello, in the build_features function, there is currently a limit of only allowing 1 entry per filter. 
Code snippet below.
```
def build_filters(json_col: Column, filters: Dict):
    """
    PRIVATE

    Builds filters for SQL query based on provided dictionary.

    Args:
        json_col (Column): The column in the database table.
        filters (Dict): The dictionary specifying filter conditions.

    Raises:
        FilterError: If filter conditions are not correctly formatted.

    Returns:
        The filter clause for the SQL query.
    """

    if not isinstance(filters, dict):
        raise FilterError("filters must be a dict")

    if len(filters) > 1:
        raise FilterError("max 1 entry per filter")
```

In my example, my filters are 
```
{'agent_id': {'$eq': 139}, 'thread_id': {'$eq': 139}}
```
and filtering is done through llama-index.

This should be removed.

# Rationale
[rationale]: #rationale

The limit makes it significantly harder to build useful applications that leverage vecs/supabase as the storage of choice for the RAG datastore. This limitation is not documented anywhere and if I had read that you could only filter by one data point in your json metadata, I would have gone with another option. Being able to filter by multiple metadata fields when doing a vector search is something I and many others will need to be able to do for complex RAG systems. 

# Design
[design]: #design

An dense explanation in sufficient detail that someone familiar with the
project could implement the feature. Specifics and corner cases should be covered.

# Examples
[examples]: #examples

Illustrations and examples to clarify descriptions from previous sections.

# Drawbacks
[drawbacks]: #drawbacks

What are the negative trade-offs?

# Alternatives
[alternatives]: #alternatives

What other solutions have been considered?

# Unresolved Questions
[unresolved]: #unresolved-questions

What parts of problem space or proposed designs are unknown or TBD?

**Comment by VictorAny** [comment]
Actually after looking at this, it looks like the llama-index SupabaseVectorStore is the one that is causing this issue. 
Specifically this code. It should be creating `{"$and": [{"agent_id": {"$eq": 136}}, {"thread_id": {"$eq": xx"}}]` instead of 
`{'agent_id': {'$eq': 139}, 'thread_id': {'$eq': 139}}`

Specifically this function is the culprit.
```
    def _to_vecs_filters(self, filters: MetadataFilters) -> Any:
        """Convert llama filters to vecs filters. $eq is the only supported operator."""
        vecs_filter = {}
        for f in filters.legacy_filters():
            vecs_filter[f.key] = {"$eq": f.value}
        return vecs_filter
```

**Comment by VictorAny** [comment]
I was able to fix this by creating my own VectorStore and using the following function to correctly handle metadata queries with multiple values. I'll make a PR request to llama-index. Thanks! 

```
 def _to_vecs_filters(self, filters: MetadataFilters) -> Any:
        """Convert llama filters to vecs filters. $eq is the only supported operator."""
        vecs_filter = {}
        if len(filters.filters) == 0:
            for f in filters.legacy_filters():
                vecs_filter[f.key] = {"$eq": f.value}
        else:
            filter_cond = "${}".format(filters.condition.value)
            vecs_filter[filter_cond] = []
            for f in filters.filters:
                sub_filter = {}
                sub_filter[f.key] = {"$eq": f.value}
                vecs_filter[filter_cond].append(sub_filter)
        return vecs_filter
```

**Comment by olirice** [comment]
>  I'll make a PR request to llama-index

thanks! much appreciated
