### ISSUE TITLE
Adding another column in collections to store raw text

### ISSUE THREAD

**Issue by sonduong305** [supabase/vecs#70]
As the title suggests, some other vector databases often have 'id,' 'metadata,' and 'embedding' columns, which Vecs supports here. However, they also support a raw text field (documents in Choma) for storing raw texts. Should it be an optional argument to add a 'text' field to the collection table? Or do you have any advice on how we should handle such a case in PgVector?

**Comment by olirice** [comment]
There are two options available currently

1. Use the string as the `id` 
This would work for sentence level embeddings but I wouldn't recommend it for longer strings

2. Add the string in the metadata field
```
{"text_body": "..."}
```
and optionally return it when querying by setting `include_metadata=True`
https://github.com/supabase/vecs/blob/fb36966278d46c0c34ebbe659b441d47a896005d/src/vecs/collection.py#L454

---

embeddings aren't specific to text so we've shied away from adding an content specific columns

I'm going to close this issue but please follow up if you have any questions
