### ISSUE TITLE
str object is not callable 

### ISSUE THREAD

**Issue by legaltextai** [supabase/vecs#75]
After I added my items to the table I run indexing and get this error: 

`docs.index()`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-3-d199780f7211>](https://localhost:8080/#) in <cell line: 1>()
----> 1 docs.index()

TypeError: 'str' object is not callable
```

**Comment by legaltextai** [comment]
btw, is 'measure' supposed to be listed twice here? 
<img width="901" alt="Screenshot 2024-02-08 at 7 55 35 AM" src="https://github.com/supabase/vecs/assets/144342123/accbac93-8746-4409-81e5-80c65ec813ea">

**Comment by olirice** [comment]
> After I added my items to the table I run indexing and get this error:
>
> docs.index()

`docs.index()` is a private method that returns the name of the index, or None, if no index exists.

I think you want to call `docs.create_index`

> btw, is 'measure' supposed to be listed twice here?

yes, thank you. I'll fix that doctoring

**Comment by legaltextai** [comment]
> > After I added my items to the table I run indexing and get this error:
> > docs.index()
> 
> `docs.index()` is a private method that returns the name of the index, or None, if no index exists.
> 
> I think you want to call `docs.create_index`
> 
> > btw, is 'measure' supposed to be listed twice here?
> 
> yes, thank you. I'll fix that doctoring

of course, create_index! sorry. 
btw, which one is that? hnsw , vector_cosine_ops?

**Comment by legaltextai** [comment]
thank you!
