### ISSUE TITLE
Why the ID field can only be the "str" type?

### ISSUE THREAD

**Issue by poloniki** [supabase/vecs#82]
Good day,
I was just wondering, why not to allow int id fields? Don't they take less space and are more efficient? I know i can change the type in the database but maybe there is some specific reason for that? 
Regards,
Nikita

**Comment by olirice** [comment]
Hi,

this choice was made:
- for consistency with other vector db clients to make migrating eaiser
- so the "id" can contain a sentence or two of text for text embedding use cases
- to make it feel more "pythonic" like a dictionary mapping from `text -> embedding`

you're absolutely right that fixed sized values like integers are more efficient primary keys. In this case, the cost of vector significantly outweighs the primary key difference so we went for usability over a marginal performance gain
