### ISSUE TITLE
SCRAM exchange: Wrong password

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [supabase/vecs#83]
Working with Supabase vecs library. I am to connect with supabase using `psycopg2.connect()` by passing a URI string variables but when I try to use the `vecs.create_client() `with the same URI string (string not variables)then it gives me this error. I tried to find a solution but couldn't find any apart from installing 2.9.3 version of psycopg2 but that didn't help either. What could be the possible problem?

**Comment by olirice** [comment]
I'd suggest checking out https://supabase.github.io/vecs/0.4/hosting/ to see where you can grab your vecs compatible connection string from Supabase Studio and how to format it.

If you have trouble after that please open a [support issue](https://supabase.com/dashboard/support/new) and we'll have visibility into your project's specifics to help track down what's going wrong
