### ISSUE TITLE
I need to have 'filters' but it needs to be empty 

### ISSUE THREAD

**Issue by legaltextai** [supabase/vecs#87]
i need to have filters on, but sometimes it needs to be empty and return all results ignoring any filters
what 's the correct syntax in this case should be? 
thank you ! 
```
result = docs.query(
...
    filters={"date": {"$eq": date_variable}} #date variable sometimes will be empty 
)
```

**Comment by olirice** [comment]
There is no override within vecs filters that allows filters to be ignored. If you want skip the filters some of the time you need to exclude the `filter` argument or pass `None`


Something like:
```python
result = docs.query(
    ...
    filters=lambda date_variable: {"date": {"$eq": date_variable}} if date_variable is not None else None 
)
```
would work if you're trying not to refactor much

**Comment by legaltextai** [comment]
thanks! ended up with passing None and it worked and ignored the filter field
