### ISSUE TITLE
can't find relevant entries

### ISSUE THREAD

**Issue by legaltextai** [supabase/vecs#89]
I 've used vecs library to create a table and upload embeddings
For the index part, instead of docs.create_index(), I ran sql command CREATE INDEX ON table USING hnsw (embeddings vector_cosine_ops); 
Is it supposed to operate similiarly? The problem is that I don't find many relevant entries when running docs.query ... now. 
I hope I don't need to re-index as it took me almost a week to build it. 
Thank you

**Comment by olirice** [comment]
vecs is a tightly scoped library that isn't designed with user started DDL commands in mind

> The problem is that I don't find many relevant entries when running docs.query

the most likely culprit is that the parameters that can be specified during index construction aren't appropriate for the data

you can read more about vecs defaults here https://github.com/supabase/vecs/blob/0dd987aac8f8dcdd68cc74e2a3dd66881d62d31f/src/vecs/collection.py#L797-L811

but I'd recommend building your indexes using the `create_index` method vs custom DDL in the future to avoid any incompatibilities

**Comment by legaltextai** [comment]
at the moment both vecs query and 
```
SELECT *
    FROM vecs.my_table
    ORDER BY vec <=> %s::vector
    LIMIT %s; 

```   yield the same results , and the results are very suboptimal 
   did I make a huge mistake by launching the default pgvector hnsw indexing instead of using vecs one? are the defaults in vecs indexing different from defaults in hnsw pgvector? 
is there an easy way to remedy it, without running another index for a week? add keyword indexing to turn into hybrid search? 
thank you

**Comment by legaltextai** [comment]
`create index ix_vector_cosine_ops_hnsw_m16_efc64_33a8f6e
                              on vecs."harvard_cold"
                              using hnsw (vec vector_cosine_ops) WITH (m=16, ef_construction=64);`

aren't these the defaults for pgvector too?

**Comment by olirice** [comment]
> aren't these the defaults for pgvector too?

yes, those are the defaults in pgvector

>  I don't find many relevant entries when running docs.quer

without knowing more about your application its difficult for me to help you with this. Are you sure there are relevant entries in the dataset?

> did I make a huge mistake by launching the default pgvector hnsw indexing instead of using vecs one?

it sounds like you're probably fine. The `collection.index` method probably doesn't work which will cause the lib to through a warning but if you selected `vector_cosine_ops` correctly then it should still be used

HNSW indexes don't like it if you have aggressive filters other than similarity search
I'd first check if you're happy with the results using semantic search only (using vecs)

I'd recommend checking out our hybrid search guide https://supabase.com/docs/guides/ai/hybrid-search

you can also read more about parameterizing ef_construction and m in [our docs](https://supabase.com/docs/guides/ai/going-to-prod#hnsw-understanding-efconstruction--efsearch--and-m)
