### ISSUE TITLE
how to index a table with 4096 dimension vectors? 

### ISSUE THREAD

**Issue by legaltextai** [supabase/vecs#92]
Is it possible? the default indexing with hnsw does not permit more than 2k dimensions. 
thank you

**Comment by olirice** [comment]
an indexing maximum of 2k dimensions is a restriction of pgvector

for performance reasons you most likely would not want embeddings of that size
In some cases, like OpenAI models you can make use of them being matryoshka embeddings to reduce the dimensionality with very little loss of accuracy 

Here's a link to the [blog](https://supabase.com/blog/matryoshka-embeddings) post about that

**Comment by legaltextai** [comment]
Thank you Oliver
