### ISSUE TITLE
create_index takes forever

### ISSUE THREAD

**Issue by mengxi-ream** [supabase/vecs#94]
**Describe the bug**

**To Reproduce**
I have some embedding to be upsert:
```python
        transcript = vx.get_or_create_collection(name="Transcript", dimension=DIMENSION)
        transcript.upsert(records=embeddings)
        transcript.create_index()
```
The first time it works, but the second time I run it, it gets stuck there (`create_index()`) forever.

**Expected behavior**
I'm not sure should I use `create_index()` every time when I upsert something? If I just need to create_index at the first time, how can I check if I created it or not in program (because the previous scripts will run several every day as a cron job)

**Screenshots**

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - vecs version: e.g. 0.2.6

**Additional context**

**Comment by olirice** [comment]
> I'm not sure should I use create_index() every time when I upsert something?

You should only call `create_index` once. After that any newly inserted records will be included in the index

It  is likely hanging because repeatedly calling `create_index` exhuasted disk io is exhausted or something like that

I'll close this for now but feel free to follow up in this thread if you have any trouble

**Comment by mengxi-ream** [comment]
> > I'm not sure should I use create_index() every time when I upsert something?
> 
> 
> 
> You should only call `create_index` once. After that any newly inserted records will be included in the index
> 
> 
> 
> It  is likely hanging because repeatedly calling `create_index` exhuasted disk io is exhausted or something like that
> 
> 
> 
> I'll close this for now but feel free to follow up in this thread if you have any trouble
> 
> 

is there any way to know if I create index before programmatically. Then when I deploy my python spider with different supsbsase instance (dev, prod), or deploy spider, then the program know if it should create index or not?

**Comment by olirice** [comment]
Its a private method but you could use
```python
Collection.index -> Optional[str]
```

if it returns `None` then there is no index, if it returns a string then their is an index

**Comment by mengxi-ream** [comment]
> Its a private method but you could use
> 
> ```python
> Collection.index -> Optional[str]
> ```
> 
> if it returns `None` then there is no index, if it returns a string then their is an index
> 
> so
> 
> ```python
> transcript.index
> ```

Oh thank you! By the way, can we design some public function that shows if it has been indexed or not? Do you think this is a good idea?

**Comment by olirice** [comment]
I'd prefer not to create a public function for it. It seems in your case you don't necessarily know if you've created the index already or not but I don't think thats a common issue

If others present with a similar concern we may reevaluate
