### ISSUE TITLE
Feature Request: Add support for custom table definition and column types

### ISSUE THREAD

**Issue by AmeanAsad** [supabase/vecs#96]
# Summary
[summary]: #summary

Currently the library enforces the following column types: https://github.com/supabase/vecs/blob/c893d569fa7126154259e0cf7c99618d35e41f6e/src/vecs/collection.py#L322

The request here is to allow the user to define extra columns as needed for certain functionality (outlined below). 

# Rationale
[rationale]: #rationale

a lot of vector db use cases have the chunked embeddings reference a specific document that is in another table. Would be great if we can define custom columns to explicitly reference that document id as part of the embedding table definition. 

The following use cases immediately come to mind:
- This seems needed to define RLS policies on the embeddings table.
-  This makes it much more efficient to query the associated documents after receiving a few embeddings as a result of a similarity search. 

# Design
[design]: #design

TBD. Happy to come up with a design for this if the request and rationale are accepted. Also happy to contribute with a PR once a design is agreed upon.

**Comment by olirice** [comment]
`Metadata` column is json and can include any references you need

If you want foreign key enforcement or dedicated columns I'd recommend checking out https://github.com/pgvector/pgvector-python for lower level support of SQL primitives

**Comment by AmeanAsad** [comment]
thanks for the response @olirice. I took a look at `pgvector-python`. It provides the low level support to define custom tables, even though it does lack some of the nice features of `vecs` like abstracting the index creation, filtering, etc. 

 If you don't mind I want to clarify the reasoning here, is this feature completely out of the scope of the `vecs` library or is it something that might get added in the future. If it is the latter, I am happy to implement this functionality myself. 

I am aware that the `Metadata` column can be used for references, but it is highly inefficient for large queries, prevents the user from using things like RLS, runs into issues with deleting documents that are still referenced by embeddings, etc. Even though it is usable, these issues make it much less production and scale friendly in my opinion. 

Hope its okay to continue the discussion after the issue has been closed, I just want to be totally sure that this feature is out of the question for the maintainers before trying to pursue building something custom. If there is a chance to build on what exists, happy to take it :)

**Comment by olirice** [comment]
Its very unlikely that we'd offer an alternative way to add metadata columns. It sounds like that would be just the starting point for what you really need:
- metadata in dedicated columns
- ability to add foreign keys
- ability to create row level security policies

The scope for this project is to get data scientists going from 0-1 as easily as possible. For applications with more advanced needs I'd recommend dropping down to that lower level so you have full control of what's happening in the SQL layer. I think the abstractions would be too leaky or the implementation to inefficient if we attempt to implement that those interfaces in vecs
