### ISSUE TITLE
Version was bumped to 0.4.5 but never pushed to PyPi

### ISSUE THREAD

**Issue by vanakema** [supabase/vecs#99]
The `vecs` version was bumped to 0.4.5 in this commit: https://github.com/supabase/vecs/commit/192177d89e13f6832abda40157d812d8b149cb8a

But that version was never pushed to PyPi. That means that on the latest version of `vecs` on PyPi, it still requires `pgvector==0.1.*`

Can we get the latest version actually published to PyPi? I can't use this library otherwise.

On a broader note, is this repo actually being actively maintained? The activity seems very low. But it does provide the level of abstraction I am looking for in my project.

**Comment by olirice** [comment]
thanks for the ping
published
https://pypi.org/project/vecs/0.4.5/

**Comment by olirice** [comment]
Yes it is maintained, but the scope is narrow so there haven't been many updates recently

**Comment by vanakema** [comment]
Would you potentially be interested in chatting? I know this lib is narrowly scoped to vectors, but I've been thinking about the lack of similar library for doing FTS using psql's tsvector. The level of abstraction would be the same as what you've got here. The idea being to decouple both keyword and vector storage and search from the rest of the application database/schema. I'm very much interested in keep it similarly lightweight as this library currently is, just expanding it to include FTS and gain some efficiencies in storage and latency

I do realize you've mentioned in a previous issue that this library was meant to help data scientists get from 0 to 1, and that you recommend using lower level libs in production, but it feels like a bad smell to essentially reimplementing what you've done here for pgvec myself and doing the same for fts when I think it can be easily expanded to FTS while also getting some potential "synergistic" gains with how we represent and query that data

**Comment by vanakema** [comment]
And not to keep putting on for `vecs` but again, it's pretty much exactly what I was imagining in my head. 

Korvus abstracts way too much, and has no python SDK to just provide vector/keyword store abstractions. pgvector-python provides no opinionation or real abstraction for "vector store" creation. `vecs` is right at that level where I have an almost perfect level of control over how I handle our data processing pipelines, while abstracting away things that get kind of ugly looking when using an ORM. Dynamically creating tables using an ORM feels like such a bad smell. I much prefer providing a "vector/keyword first" abstraction than trying to wrangle an ORM into doing what I want and figuring out how to make it look all clean and abstracted in my codebase (which I currently have done, but it feels kind of out of place with the rest of the patterns)

**Comment by olirice** [comment]
sorry for the slow reply

FTS has a lot more surface area to cover than pgvector due to interactions among dictionaries, stop words, stemming, pgroonga, pg_tgrm, tsvector, etc etc which make it much more challenging to create a clean abstraction over. If anything I think that makes a well thought out interface more valuable vs less valuable but it also makes it a project that's bigger than we would want to tackle within vecs.

did you have an API in mind?
